# -*- coding: utf-8 -*-
"""StructStudent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgYG6VWboIUwr-B6t4Oeo6W2B_lLencA

Lect05_Struct Student
"""

class Student:
    def __init__(self):
        self.name = "Rahul"
        self.roll = 101
        self.marks = 87.5


s1 = Student()

print("Name:", s1.name)
print("Roll:", s1.roll)
print("Marks:", s1.marks)